/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class asus_jerry_chen_gr_MyString */

#ifndef _Included_asus_jerry_chen_gr_MyString
#define _Included_asus_jerry_chen_gr_MyString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     asus_jerry_chen_gr_MyString
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_asus_jerry_1chen_gr_MyString_getStringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
